export const NOTIONAL_AVG_RATING = 90;

export const TEAMS = {
    ADELAIDE: 'Adelaide',
    BRISBANE: 'Brisbane',
    BULLDOGS: 'Western Bulldogs',
    CARLTON: 'Carlton',
    COLLINGWOOD: 'Collingwood',
    ESSENDON: 'Essendon',
    FREMANTLE: 'Fremantle',
    GEELONG: 'Geelong',
    GIANTS: 'GWS Giants',
    GOLD_COAST: 'Gold Coast',
    HAWTHORN: 'Hawthorn',
    MELBOURNE: 'Melbourne',
    NORTH_MELBOURNE: 'North Melbourne',
    PORT_ADELAIDE: 'Port Adelaide',
    RICHMOND: 'Richmond',
    ST_KILDA: 'St Kilda',
    SYDNEY: 'Sydney',
    WEST_COAST: 'West Coast',
};

export const LOGO_PATHS = {
    [TEAMS.ADELAIDE]: 'adelaide',
    [TEAMS.BRISBANE]: 'brisbane',
    [TEAMS.BULLDOGS]: 'bulldogs',
    [TEAMS.CARLTON]: 'carlton',
    [TEAMS.COLLINGWOOD]: 'collingwood',
    [TEAMS.ESSENDON]: 'essendon',
    [TEAMS.FREMANTLE]: 'fremantle',
    [TEAMS.GEELONG]: 'geelong',
    [TEAMS.GIANTS]: 'giants',
    [TEAMS.GOLD_COAST]: 'goldCoast',
    [TEAMS.HAWTHORN]: 'hawthorn',
    [TEAMS.MELBOURNE]: 'melbourne',
    [TEAMS.NORTH_MELBOURNE]: 'northMelbourne',
    [TEAMS.PORT_ADELAIDE]: 'portAdelaide',
    [TEAMS.RICHMOND]: 'richmond',
    [TEAMS.ST_KILDA]: 'stKilda',
    [TEAMS.SYDNEY]: 'sydney',
    [TEAMS.WEST_COAST]: 'westCoast',
};

export const TEAM_COLORS = {
    [TEAMS.ADELAIDE]: { primary: '#004B8D', secondary: '#FFD200' },
    [TEAMS.BRISBANE]: { primary: '#8B0042', secondary: '#EDC157' },
    [TEAMS.BULLDOGS]: { primary: '#06357A', secondary: '#C60C30' },
    [TEAMS.CARLTON]: { primary: '#031E2F', secondary: '#031E2F' },
    [TEAMS.COLLINGWOOD]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.ESSENDON]: { primary: '#000000', secondary: '#C90527' },
    [TEAMS.FREMANTLE]: { primary: '#331C54', secondary: '#331C54' },
    [TEAMS.GEELONG]: { primary: '#002244', secondary: '#002244' },
    [TEAMS.GOLD_COAST]: { primary: '#E02112', secondary: '#FFDD00' },
    [TEAMS.GIANTS]: { primary: '#343433', secondary: '#FF7900' },
    [TEAMS.HAWTHORN]: { primary: '#562500', secondary: '#FFC400' },
    [TEAMS.MELBOURNE]: { primary: '#061A33', secondary: '#DE0316' },
    [TEAMS.NORTH_MELBOURNE]: { primary: '#003CA0', secondary: '#003CA0' },
    [TEAMS.PORT_ADELAIDE]: { primary: '#000105', secondary: '#008AAB' },
    [TEAMS.RICHMOND]: { primary: '#000000', secondary: '#FFD300' },
    [TEAMS.ST_KILDA]: { primary: '#000000', secondary: '#E00034' },
    [TEAMS.SYDNEY]: { primary: '#EE1E31', secondary: '#EE1E31' },
    [TEAMS.WEST_COAST]: { primary: '#003087', secondary: '#F2A900' },
};

export const FINALS_ROUNDS = [
    { roundNum: 19, label: 'EF/QF' },
    { roundNum: 20, label: 'SF' },
    { roundNum: 21, label: 'PF' },
    { roundNum: 22, label: 'GF' },
];
