export const NOTIONAL_AVG_RATING = 90;

export const TEAMS = {
    ADELAIDE: 'Adelaide',
    BRISBANE: 'Brisbane',
    BULLDOGS: 'Western Bulldogs',
    CARLTON: 'Carlton',
    COLLINGWOOD: 'Collingwood',
    ESSENDON: 'Essendon',
    FREMANTLE: 'Fremantle',
    GEELONG: 'Geelong',
    GIANTS: 'GWS Giants',
    GOLD_COAST: 'Gold Coast',
    HAWTHORN: 'Hawthorn',
    MELBOURNE: 'Melbourne',
    NORTH_MELBOURNE: 'North Melbourne',
    PORT_ADELAIDE: 'Port Adelaide',
    RICHMOND: 'Richmond',
    ST_KILDA: 'St Kilda',
    SYDNEY: 'Sydney',
    WEST_COAST: 'West Coast',
};

export const LOGO_PATHS = {
    [TEAMS.ADELAIDE]: 'adelaide',
    [TEAMS.BRISBANE]: 'brisbane',
    [TEAMS.BULLDOGS]: 'bulldogs',
    [TEAMS.CARLTON]: 'carlton',
    [TEAMS.COLLINGWOOD]: 'collingwood',
    [TEAMS.ESSENDON]: 'essendon',
    [TEAMS.FREMANTLE]: 'fremantle',
    [TEAMS.GEELONG]: 'geelong',
    [TEAMS.GIANTS]: 'giants',
    [TEAMS.GOLD_COAST]: 'goldCoast',
    [TEAMS.HAWTHORN]: 'hawthorn',
    [TEAMS.MELBOURNE]: 'melbourne',
    [TEAMS.NORTH_MELBOURNE]: 'northMelbourne',
    [TEAMS.PORT_ADELAIDE]: 'portAdelaide',
    [TEAMS.RICHMOND]: 'richmond',
    [TEAMS.ST_KILDA]: 'stKilda',
    [TEAMS.SYDNEY]: 'sydney',
    [TEAMS.WEST_COAST]: 'westCoast',
};

export const TEAM_COLORS = {
    [TEAMS.ADELAIDE]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.BRISBANE]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.BULLDOGS]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.CARLTON]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.COLLINGWOOD]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.ESSENDON]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.FREMANTLE]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.GEELONG]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.GOLD_COAST]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.GWS]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.HAWTHORN]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.MELBOURNE]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.NORTH_MELBOURNE]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.PORT_ADELAIDE]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.RICHMOND]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.ST_KILDA]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.SYDNEY]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.WEST_COAST]: { primary: '#000000', secondary: '#000000' },
};
