export const TEAMS = {
    ADELAIDE: 'adelaide',
    BRISBANE: 'brisbane',
    BULLDOGS: 'bulldogs',
    CARLTON: 'carlton',
    COLLINGWOOD: 'collingwood',
    ESSENDON: 'essendon',
    FREMANTLE: 'fremantle',
    GEELONG: 'geelong',
    GIANTS: 'giants',
    GOLD_COAST: 'goldCoast',
    HAWTHORN: 'hawthorn',
    MELBOURNE: 'melbourne',
    NORTH_MELBOURNE: 'northMelbourne',
    PORT_ADELAIDE: 'portAdelaide',
    RICHMOND: 'richmond',
    ST_KILDA: 'stKilda',
    SYDNEY: 'sydney',
    WEST_COAST: 'westCoast',
};

export const TEAM_NAMES = {
    [TEAMS.ADELAIDE]: 'Adelaide',
    [TEAMS.BRISBANE]: 'Brisbane',
    [TEAMS.BULLDOGS]: 'Bulldogs',
    [TEAMS.CARLTON]: 'Carlton',
    [TEAMS.COLLINGWOOD]: 'Collingwood',
    [TEAMS.ESSENDON]: 'Essendon',
    [TEAMS.FREMANTLE]: 'Fremantle',
    [TEAMS.GEELONG]: 'Geelong',
    [TEAMS.GIANTS]: 'Greater Western Sydney',
    [TEAMS.GOLD_COAST]: 'Gold Coast',
    [TEAMS.HAWTHORN]: 'Hawthorn',
    [TEAMS.MELBOURNE]: 'Melbourne',
    [TEAMS.NORTH_MELBOURNE]: 'North Melbourne',
    [TEAMS.PORT_ADELAIDE]: 'Port Adelaide',
    [TEAMS.RICHMOND]: 'Richmond',
    [TEAMS.ST_KILDA]: 'St Kilda',
    [TEAMS.SYDNEY]: 'Sydney',
    [TEAMS.WEST_COAST]: 'West Coast',
};

export const TEAM_COLORS = {
    [TEAMS.ADELAIDE]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.BRISBANE]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.BULLDOGS]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.CARLTON]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.COLLINGWOOD]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.ESSENDON]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.FREMANTLE]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.GEELONG]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.GOLD_COAST]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.GWS]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.HAWTHORN]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.MELBOURNE]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.NORTH_MELBOURNE]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.PORT_ADELAIDE]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.RICHMOND]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.ST_KILDA]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.SYDNEY]: { primary: '#000000', secondary: '#000000' },
    [TEAMS.WEST_COAST]: { primary: '#000000', secondary: '#000000' },
};